### ISSUE TITLE
Inappropriate calculation of next expectation deadline

### ISSUE THREAD

**Issue by aenglund** [monlog/monlog#47]
There is an issue on calculating the next expectation deadline. Since the next deadline is  calculated based on the current deadline there will be issues when months differ in days. 

Example:
Deadline sat at January 31 with one month repeat setting.
January 31 -> February 28 -> March 28

Expected deadline:
January 31 -> February 28 -> March 31

Sorry guys, had problems finding something interesting to do on the train back home ;).

**Comment by trew** [comment]
Nice find. This is a severe bug and luckily easily fixed. :-)

**Comment by trew** [comment]
References wrong pull request at first -.-
